### ISSUE TITLE
ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method openPlaceAutocomplete on channel mapmyindia_place_flutter

### ISSUE THREAD

**Issue by antonio-pedro99** [mappls-api/flutter-mapmyindia-gl#7]
My flutter environment is working fine.

I am trying to use the openPlacePicker() function from mapmyindia_place_widgets, but I am keeping getting this error while trying to invoke the function.

**Comment by ajay-k07** [comment]
You can try flutter clean and try to rerun 
Please attach the full error message

**Comment by antonio-pedro99** [comment]
Done.

**Comment by antonio-pedro99** [comment]
it worked, thanks!

**Comment by ajay-k07** [comment]
no problem Enjoy
